let licenseHeader = """
# SPDX-FileCopyrightText: 2014-2022 Rik van der Kleij
# SPDX-FileCopyrightText: 2014-2022 intellij-haskell contributors <https://github.com/rikvdkleij/intellij-haskell>
# SPDX-FileCopyrightText: 2026 haskeletor contributors <https://github.com/ForNeVeR/haskeletor>
#
# SPDX-License-Identifier: Apache-2.0

# This file is auto-generated by scripts/github-actions.fsx""".Trim()

#r "nuget: Generaptor.Library, 1.11.0"

open Generaptor
open Generaptor.GitHubActions

open type Generaptor.GitHubActions.Commands

let workflows = [
    let defaultLinux = "ubuntu-24.04"
    let runners = [
        "macos-15"
        "ubuntu-24.04-arm"
        "windows-2025"
        defaultLinux
    ]

    let workflow name body = workflow name [
        header licenseHeader
        yield! body
    ]

    workflow "main" [
        name "Gradle CI"
        onPushTo "master"
        onPushTo "renovate/**"
        onPullRequestTo "master"

        let sourceJob name body = job name [
            step(
                name = "Check out the sources",
                usesSpec = Auto "actions/checkout"
            )
            yield! body
        ]

        sourceJob "build" [
            strategy(failFast = false, matrix = [
                "image", runners
            ])
            runsOn "${{ matrix.image }}"

            step(
                name = "Cache downloaded JDK",
                usesSpec = Auto "actions/cache",
                options = Map.ofList [
                    "path", [
                        "~/.local/share/gradle-jvm"
                        "~/AppData/Local/gradle-jvm"
                    ] |> String.concat "\n"
                    "key", "${{ runner.os }}.jvm.${{ hashFiles('gradlew*') }}"
                ]
            )
            step(
                name = "Setup Gradle",
                usesSpec = Auto "gradle/actions/setup-gradle"
            )
            step(
                name = "Build plugin",
                run = "./gradlew buildPlugin"
            )
            step(
                name = "Run tests",
                run = "./gradlew test"
            )
        ]
        sourceJob "encoding" [
            runsOn defaultLinux

            step(
                name = "Verify encoding",
                shell = "pwsh",
                run = "Install-Module VerifyEncoding -Repository PSGallery -RequiredVersion 2.3.0 -Force && Test-Encoding -ExcludeExtensions '.bat', '.DotSettings'"
            )
        ]
        sourceJob "licenses" [
            runsOn defaultLinux

            step(
                name = "REUSE license check",
                usesSpec = Auto "fsfe/reuse-action"
            )
        ]
        sourceJob "verify-workflows" [
            runsOn defaultLinux

            setEnv "DOTNET_CLI_TELEMETRY_OPTOUT" "1"
            setEnv "DOTNET_NOLOGO" "1"
            setEnv "NUGET_PACKAGES" "${{ github.workspace }}/.github/nuget-packages"

            step(
                name = "Set up .NET SDK",
                usesSpec = Auto "actions/setup-dotnet"
            )
            step(
                name = "Verify workflows",
                run = "dotnet fsi ./scripts/github-actions.fsx verify"
            )
        ]
    ]
]
exit <| EntryPoint.Process fsi.CommandLineArgs workflows
