let licenseHeader = """
# SPDX-FileCopyrightText: 2014-2022 Rik van der Kleij
# SPDX-FileCopyrightText: 2014-2022 intellij-haskell contributors <https://github.com/rikvdkleij/intellij-haskell>
# SPDX-FileCopyrightText: 2026 haskeletor contributors <https://github.com/ForNeVeR/haskeletor>
#
# SPDX-License-Identifier: Apache-2.0

# This file is auto-generated by scripts/github-actions.fsx""".Trim()

#r "nuget: Generaptor.Library, 1.11.0"

open Generaptor
open Generaptor.GitHubActions

open type Generaptor.GitHubActions.Commands

let workflows = [
    let defaultLinux = "ubuntu-24.04"
    let runners = [
        "macos-15"
        "ubuntu-24.04-arm"
        "windows-2025"
        defaultLinux
    ]

    let workflow name body = workflow name [
        header licenseHeader
        yield! body
    ]

    let mainTriggers = [
        onPushTo "master"
        onPushTo "renovate/**"
        onPullRequestTo "master"
    ]

    let sourceJob name body = job name [
        step(
            name = "Check out the sources",
            usesSpec = Auto "actions/checkout"
        )
        yield! body
    ]

    workflow "main" [
        name "Gradle CI"
        yield! mainTriggers

        sourceJob "build" [
            strategy(failFast = false, matrix = [
                "image", runners
            ])
            runsOn "${{ matrix.image }}"

            step(
                name = "Cache downloaded JDK",
                usesSpec = Auto "actions/cache",
                options = Map.ofList [
                    "path", [
                        "~/.local/share/gradle-jvm"
                        "~/AppData/Local/gradle-jvm"
                    ] |> String.concat "\n"
                    "key", "${{ runner.os }}.jvm.${{ hashFiles('gradlew*') }}"
                ]
            )
            step(
                name = "Setup Gradle",
                usesSpec = Auto "gradle/actions/setup-gradle"
            )
            step(
                name = "Build plugin",
                run = "./gradlew buildPlugin"
            )
            step(
                name = "Run tests",
                run = "./gradlew test"
            )
        ]
        sourceJob "encoding" [
            runsOn defaultLinux

            step(
                name = "Verify encoding",
                shell = "pwsh",
                run = "Install-Module VerifyEncoding -Repository PSGallery -RequiredVersion 2.3.0 -Force && Test-Encoding -ExcludeExtensions '.bat', '.DotSettings'"
            )
        ]
        sourceJob "licenses" [
            runsOn defaultLinux

            step(
                name = "REUSE license check",
                usesSpec = Auto "fsfe/reuse-action"
            )
        ]
        sourceJob "verify-workflows" [
            runsOn defaultLinux

            setEnv "DOTNET_CLI_TELEMETRY_OPTOUT" "1"
            setEnv "DOTNET_NOLOGO" "1"
            setEnv "NUGET_PACKAGES" "${{ github.workspace }}/.github/nuget-packages"

            step(
                name = "Set up .NET SDK",
                usesSpec = Auto "actions/setup-dotnet"
            )
            step(
                name = "Verify workflows",
                run = "dotnet fsi ./scripts/github-actions.fsx verify"
            )
        ]
    ]

    workflow "release" [
        name "Release"
        yield! mainTriggers
        onPushTags "v*"

        sourceJob "release" [
            runsOn defaultLinux
            jobPermission(PermissionKind.Contents, AccessKind.Write)

            step(
                id = "version",
                name = "Get version",
                shell = "pwsh",
                run = "\"version=$(scripts/Get-Version.ps1 -RefName $env:GITHUB_REF)\" >> $env:GITHUB_OUTPUT"
            )

            step(
                name = "Read the changelog",
                usesSpec = Auto "ForNeVeR/ChangelogAutomation.action",
                options = Map.ofList [
                    "input", "./CHANGELOG.md"
                    "output", "./release-notes.md"
                ]
            )
            step(
                name = "Upload the changelog",
                usesSpec = Auto "actions/upload-artifact",
                options = Map.ofList [
                    "name", "release-notes.md"
                    "path", "./release-notes.md"
                ]
            )

            step(
                name = "Cache downloaded JDK",
                usesSpec = Auto "actions/cache",
                options = Map.ofList [
                    "path", "~/.local/share/gradle-jvm"
                    "key", "${{ runner.os }}-${{ hashFiles('gradlew*') }}"
                ]
            )
            step(
                name = "Set up Gradle",
                usesSpec = Auto "gradle/actions/setup-gradle"
            )
            step(
                name = "Build the plugin",
                shell = "pwsh",
                run = "./gradlew buildPlugin"
            )
            step(
                name = "Upload the plugin",
                usesSpec = Auto "actions/upload-artifact",
                options = Map.ofList [
                    "name", "haskeletor-${{ steps.version.outputs.version }}.zip"
                    "path", "build/distributions/haskeletor-${{ steps.version.outputs.version }}.zip"
                ]
            )

            step(
                condition = "startsWith(github.ref, 'refs/tags/v')",
                name = "Create a release",
                usesSpec = Auto "softprops/action-gh-release",
                options = Map.ofList [
                    "body_path", "./release-notes.md"
                    "files", "build/distributions/haskeletor-${{ steps.version.outputs.version }}.zip"
                    "name", "Haskeletor v${{ steps.version.outputs.version }}"
                ]
            )
            step(
                condition = "startsWith(github.ref, 'refs/tags/v')",
                name = "Publish the plugin",
                env = Map.ofList [
                    "PUBLISH_TOKEN", "${{ secrets.PUBLISH_TOKEN }}"
                ],
                shell = "pwsh",
                workingDirectory = "intellij",
                run = "./gradlew publishPlugin"
            )
        ]
    ]
]
exit <| EntryPoint.Process fsi.CommandLineArgs workflows
