# SPDX-FileCopyrightText: 2014-2022 Rik van der Kleij
# SPDX-FileCopyrightText: 2014-2022 intellij-haskell contributors <https://github.com/rikvdkleij/intellij-haskell>
# SPDX-FileCopyrightText: 2026 haskeletor contributors <https://github.com/ForNeVeR/haskeletor>
#
# SPDX-License-Identifier: Apache-2.0

name: Gradle CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Cache downloaded JDK
      uses: actions/cache@v5
      with:
        path: |
          ~/.local/share/gradle-jvm
          ~/AppData/Local/gradle-jvm
        key: ${{ runner.os }}.jvm.${{ hashFiles('gradlew*') }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Build plugin
      run: ./gradlew buildPlugin
    - name: Run tests
      run: ./gradlew test

  encoding:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the sources
        uses: actions/checkout@v4
      - name: Verify encoding
        shell: pwsh
        run: Install-Module VerifyEncoding -Repository PSGallery -RequiredVersion 2.3.0 -Force && Test-Encoding

  licenses:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the sources
        uses: actions/checkout@v6
      - name: REUSE license check
        uses: fsfe/reuse-action@v6
